/**
 * memory-sync-hook — fires on Stop and PreCompact events.
 *
 * Exports active rules from Claude Recall's SQLite database to a topic file
 * in Claude Code's auto-memory directory, so rules are available even when
 * the MCP server is down.
 *
 * Input: { session_id, cwd, hook_event_name }
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { hookLog } from './shared';
import { MemoryService } from '../services/memory';
import { ConfigService } from '../services/config';

/** Keys that look like test data */
const TEST_KEY_PATTERNS = [/^Test /i, /^Session test /i, /^test_/i];

/** Values that may contain secrets */
const SECRET_PATTERNS = [/api_key/i, /token/i, /password/i, /secret/i, /credential/i, /private_key/i];

/**
 * Derive the auto-memory directory path from a cwd.
 * Matches Claude Code's convention: ~/.claude/projects/{cwd with / replaced by -}/memory/
 */
export function deriveAutoMemoryPath(cwd: string, homedir?: string): string {
  const home = homedir || os.homedir();
  const sanitized = cwd.replace(/\//g, '-');
  return path.join(home, '.claude', 'projects', sanitized, 'memory');
}

/**
 * Extract display value from a memory record, matching memory-tools.ts formatting.
 */
function extractValue(m: any): string {
  const val = typeof m.value === 'object'
    ? (m.value.content || m.value.value || JSON.stringify(m.value))
    : m.value;
  return String(val);
}

/**
 * Check if a memory key matches test data patterns.
 */
function isTestData(key: string): boolean {
  return TEST_KEY_PATTERNS.some(p => p.test(key));
}

/**
 * Check if a value contains secret-like content.
 */
function containsSecret(value: string): boolean {
  return SECRET_PATTERNS.some(p => p.test(value));
}

/**
 * Format rules into markdown sections.
 */
function formatRulesMarkdown(rules: {
  preferences: any[];
  corrections: any[];
  failures: any[];
  devops: any[];
}): string {
  const sections: string[] = [];

  sections.push('<!-- Auto-generated by Claude Recall — overwritten each session -->');
  sections.push('# Claude Recall Rules');

  if (rules.preferences.length > 0) {
    sections.push('\n## Preferences');
    for (const m of rules.preferences) {
      const val = extractValue(m);
      const key = m.preference_key || m.key || '';
      const isAutoKey = key.startsWith('memory_') || key.startsWith('auto_') || key.startsWith('pref_') || key.startsWith('hook_');
      sections.push(isAutoKey ? `- ${val}` : `- ${key}: ${val}`);
    }
  }

  if (rules.corrections.length > 0) {
    sections.push('\n## Corrections');
    for (const m of rules.corrections) {
      sections.push(`- ${extractValue(m)}`);
    }
  }

  if (rules.failures.length > 0) {
    sections.push('\n## Failures');
    for (const m of rules.failures) {
      sections.push(`- ${extractValue(m)}`);
    }
  }

  if (rules.devops.length > 0) {
    sections.push('\n## DevOps Rules');
    for (const m of rules.devops) {
      sections.push(`- ${extractValue(m)}`);
    }
  }

  sections.push(`\n---\n*Last synced: ${new Date().toISOString()}*`);

  return sections.join('\n') + '\n';
}

const MEMORY_MD_POINTER = `\n## Claude Recall\n- See [recall-rules.md](recall-rules.md) for learned preferences, corrections, and failure lessons\n`;

/**
 * Ensure MEMORY.md contains a pointer to recall-rules.md.
 * Appends the pointer only if absent. Never overwrites existing content.
 */
function ensureMemoryMdPointer(memoryDir: string): void {
  const memoryMdPath = path.join(memoryDir, 'MEMORY.md');

  let existing = '';
  if (fs.existsSync(memoryMdPath)) {
    existing = fs.readFileSync(memoryMdPath, 'utf-8');
  }

  if (existing.includes('recall-rules.md')) {
    return; // Pointer already present
  }

  fs.appendFileSync(memoryMdPath, MEMORY_MD_POINTER);
}

/**
 * Filter out test data and secrets from rules.
 */
function filterRules(memories: any[]): any[] {
  return memories.filter(m => {
    const key = m.preference_key || m.key || '';
    if (isTestData(key)) return false;

    const val = extractValue(m);
    if (containsSecret(val)) return false;

    return true;
  });
}

export async function handleMemorySync(input: any): Promise<void> {
  const cwd: string = input?.cwd ?? '';

  if (!cwd) {
    hookLog('memory-sync', 'No cwd provided — skipping sync');
    return;
  }

  try {
    const projectId = ConfigService.getInstance().getProjectId();
    const memoryService = MemoryService.getInstance();
    const rules = memoryService.loadActiveRules(projectId);

    // Filter each category
    const filtered = {
      preferences: filterRules(rules.preferences),
      corrections: filterRules(rules.corrections),
      failures: filterRules(rules.failures),
      devops: filterRules(rules.devops),
    };

    const totalRules = filtered.preferences.length + filtered.corrections.length +
      filtered.failures.length + filtered.devops.length;

    // Derive auto-memory path and ensure directory exists
    const memoryDir = deriveAutoMemoryPath(cwd);
    if (!fs.existsSync(memoryDir)) {
      fs.mkdirSync(memoryDir, { recursive: true });
    }

    // Write recall-rules.md (full overwrite)
    const markdown = formatRulesMarkdown(filtered);
    const rulesPath = path.join(memoryDir, 'recall-rules.md');
    fs.writeFileSync(rulesPath, markdown);

    // Ensure MEMORY.md has pointer
    ensureMemoryMdPointer(memoryDir);

    hookLog('memory-sync', `Synced ${totalRules} rules to ${rulesPath}`);
  } catch (error) {
    hookLog('memory-sync', `Error: ${(error as Error).message}`);
  }
}
